name: dropix
description: Cross-platform file transfer app using mDNS device discovery.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # mDNS discovery + registration (Bonjour/NSD)
  nsd: 4.1.0
  # Get device name & info
  device_info_plus: ^9.0.0
  # Get local IP address
  network_info_plus: ^5.0.0
  # Unique device ID
  uuid: ^4.0.0
# State management
  provider: ^6.1.0
  path_provider: ^2.1.5
  file_picker: ^10.3.10
  mobile_scanner: ^5.0.0
  qr_flutter: ^4.1.0
  flutter_local_notifications: ^21.0.0
  flutter_foreground_task: ^9.2.1
  local_notifier: ^0.1.6
  open_filex: ^4.7.0
  flutter_launcher_icons: ^0.14.4
  desktop_drop: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/dropix_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/images/dropix_logo.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/dropix_logo.png"